#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'launcher'

def options(opt):
        # stub
        return

def configure(conf):
        conf.define('LAUNCHERONLY',1)
        conf.define('CFLAGS', conf.env.CFLAGS)
        conf.define('LDFLAGS', conf.env.LINKFLAGS)

        if conf.env.DEST_OS == 'android':
                # EZQuest slice D/E: native OpenXR bootstrap compiled into
                # liblauncher.so. The loader (libopenxr_loader.so) + headers
                # come from the Khronos openxr_loader_for_android AAR, which
                # CI extracts into external/openxr/ (see build-android-arm64).
                xr_root = os.path.abspath(os.path.join(str(conf.path), '..', 'external', 'openxr'))
                xr_inc = os.path.join(xr_root, 'include')
                xr_lib = os.path.join(xr_root, 'lib', conf.env.DEST_CPU)
                if not os.path.isdir(os.path.join(xr_inc, 'openxr')):
                        conf.fatal('OpenXR loader not found under %s -- fetch the '
                                   'Khronos openxr_loader_for_android AAR first (see '
                                   '.github/workflows/build-android-arm64.yml)' % xr_root)
                conf.env.append_unique('INCLUDES_OPENXR', [xr_inc])
                conf.env.append_unique('LIBPATH_OPENXR', [xr_lib])
                conf.env.append_unique('LIB_OPENXR', ['openxr_loader', 'EGL', 'GLESv3', 'android'])
                conf.msg('OpenXR loader', xr_root)

def build(bld):
        source = [
                '../public/filesystem_init.cpp',
                'launcher.cpp',
                'reslistgenerator.cpp',
                '../public/tier0/memoverride.cpp'
        ]

        if bld.env.DEST_OS == 'android':
                source += [
                        'android/main.cpp',
                        'android/crashhandler.cpp',
                        'android/vr_main.cpp',
                        'android/vr_scene.cpp',
                        'android/vr_input.cpp',
                        'android/ezquest_vr_engine.cpp'
                ]

        includes = [
                '.',
                'android/libunwind',
                '../public',
                '../public/tier0',
                '../public/tier1',
                '../common'
        ] + bld.env.INCLUDES_SDL2

        defines = []

        libs = ['tier0','tier1','tier2','tier3','vstdlib','steam_api','appframework','SDL2','togl', 'UNWIND']

        if bld.env.DEST_OS == 'win32':
                libs += ['USER32', 'OLE32', 'SHELL32']

        # EZQuest: OpenXR loader + GLES/Android system libs for the VR path.
        if bld.env.DEST_OS == 'android':
                libs += ['OPENXR']

        install_path = bld.env.LIBDIR

        bld.shlib(
                source   = source,
                target   = PROJECT_NAME,
                name     = PROJECT_NAME,
                features = 'c cxx',
                includes = includes,
                defines  = defines,
                use      = libs,
                install_path = install_path,
                subsystem = bld.env.MSVC_SUBSYSTEM,
                idx      = bld.get_taskgen_count()
        )
